apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: angular-frontend
  annotations:
    ootb.apps.tanzu.vmware.com/servicebinding-workload: "true"
    ootb.apps.tanzu.vmware.com/apidescriptor-ref: "true"
    kapp.k14s.io/change-rule: upsert after upserting servicebinding.io/ServiceBindings
  labels:
    app.kubernetes.io/part-of: angular-frontend
    apps.tanzu.vmware.com/workload-type: web
    app.kubernetes.io/component: run
    carto.run/workload-name: angular-frontend
spec:
  template:
    metadata:
      annotations:
        apps.tanzu.vmware.com/correlationid: https://github.com/Mpluya/angular-frontend?sub_path=/
        autoscaling.knative.dev/minScale: "1"
        conventions.carto.run/applied-conventions: |-
          appliveview-sample/app-live-view-appflavour-check
          spring-boot-convention/auto-configure-actuators-check
          spring-boot-convention/app-live-view-appflavour-check
        developer.conventions/target-containers: workload
      labels:
        app.kubernetes.io/component: run
        app.kubernetes.io/part-of: angular-frontend
        apps.tanzu.vmware.com/workload-type: web
        carto.run/workload-name: angular-frontend
    spec:
      containers:
      - image: registry.harbor.learn.tapsme.org/tap-build/workloads/angular-frontend-mae@sha256:7fa9014b09b0c289ce8a4092c7882b8c496969f9cae7d0d156b60bec4bdc4252
        name: workload
        resources: {}
        securityContext:
          runAsUser: 1000
      serviceAccountName: default

