apiVersion: apis.apps.tanzu.vmware.com/v1alpha1
kind: APIDescriptor
metadata:
  name: customer-profile-too
  annotations:
    autoscaling.knative.dev/minScale: "1"
  labels:
    apis.apps.tanzu.vmware.com/register-api: "true"
    app.kubernetes.io/part-of: customer-profile-too
    apps.tanzu.vmware.com/auto-configure-actuators: "true"
    apps.tanzu.vmware.com/has-tests: "true"
    apps.tanzu.vmware.com/workload-type: web
    no-sonar: "true"
    app.kubernetes.io/component: run
    carto.run/workload-name: customer-profile-too
spec:
  type: openapi
  description: Manage customer profiles
  system: tanzu-gtt
  owner: team-awesome
  location:
    path: /api-docs
    baseURL:
      ref:
        apiVersion: serving.knative.dev/v1
        kind: Service
        name: customer-profile-too

