apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: convention-workload-with-volumes
  annotations:
    ootb.apps.tanzu.vmware.com/servicebinding-workload: "true"
    ootb.apps.tanzu.vmware.com/apidescriptor-ref: "true"
    kapp.k14s.io/change-rule: upsert after upserting servicebinding.io/ServiceBindings
  labels:
    app.kubernetes.io/part-of: convention-workload-with-volumes
    apps.tanzu.vmware.com/language: golang
    apps.tanzu.vmware.com/workload-type: web
    app.kubernetes.io/component: run
    carto.run/workload-name: convention-workload-with-volumes
spec:
  template:
    metadata:
      annotations:
        autoscaling.knative.dev/minScale: "1"
        conventions.carto.run/applied-conventions: |-
          appliveview-sample/app-live-view-appflavour-check
          jeremy-server/x95castle1.org-storage
          spring-boot-convention/auto-configure-actuators-check
          spring-boot-convention/app-live-view-appflavour-check
        developer.conventions/target-containers: workload
        kubectl.kubernetes.io/last-applied-configuration: |
          {"apiVersion":"carto.run/v1alpha1","kind":"Workload","metadata":{"annotations":{},"labels":{"app.kubernetes.io/part-of":"convention-workload-with-volumes","apps.tanzu.vmware.com/language":"golang","apps.tanzu.vmware.com/workload-type":"web"},"name":"convention-workload-with-volumes","namespace":"jeremy"},"spec":{"params":[{"name":"annotations","value":{"autoscaling.knative.dev/minScale":"1","x95castle1.org/storage":"{\"volumes\":[{\"name\":\"config-vol\",\"configMap\":{\"name\":\"log-config\",\"items\":[{\"key\":\"log_level\",\"path\":\"log_level\"}]}}],\"volumeMounts\":[{\"name\":\"config-vol\",\"mountPath\":\"/etc/config\"}]}"}}],"source":{"git":{"ref":{"branch":"main"},"url":"https://github.com/carto-run/app-golang-kpack"}}}}
        x95castle1.org/storage: '{"volumes":[{"name":"config-vol","configMap":{"name":"log-config","items":[{"key":"log_level","path":"log_level"}]}}],"volumeMounts":[{"name":"config-vol","mountPath":"/etc/config"}]}'
      labels:
        app.kubernetes.io/component: run
        app.kubernetes.io/part-of: convention-workload-with-volumes
        apps.tanzu.vmware.com/language: golang
        apps.tanzu.vmware.com/workload-type: web
        carto.run/workload-name: convention-workload-with-volumes
    spec:
      containers:
      - image: registry.harbor.learn.tapsme.org/tap-build/workloads/convention-workload-with-volumes-jeremy@sha256:d39734e34d2c5b21f4dc6c2b8d8d89f032ce2c5fb1d10a78ecdda1e66fdc6c81
        name: workload
        resources: {}
        securityContext:
          runAsUser: 1000
        volumeMounts:
        - mountPath: /etc/config
          name: config-vol
      serviceAccountName: default
      volumes:
      - configMap:
          items:
          - key: log_level
            path: log_level
          name: log-config
        name: config-vol

