apiVersion: data.packaging.carvel.dev/v1alpha1
kind: Package
metadata:
  name: petclinic.mae.tap.20230523120823.0.0
spec:
  refName: petclinic.mae.tap
  version: 20230523120823.0.0
  releaseNotes: |
    Release v20230523120823.0.0 of package petclinic.mae.tap
  template:
    spec:
      fetch:
      - imgpkgBundle:
          image: registry.harbor.learn.tapsme.org/tap-build/workloads/petclinic-mae-bundle@sha256:ae864392538f5b090f0f4ae8728ead74df7b1372cc4712d83c3fb7de6c8059a8
      template:
      - ytt:
          paths:
          - .
      - kbld:
          paths:
          - .imgpkg/images.yml
          - '-'
      deploy:
      - kapp: {}

