apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: convention-workload-tolerations
  annotations:
    ootb.apps.tanzu.vmware.com/servicebinding-workload: "true"
    ootb.apps.tanzu.vmware.com/apidescriptor-ref: "true"
    kapp.k14s.io/change-rule: upsert after upserting servicebinding.io/ServiceBindings
  labels:
    app.kubernetes.io/part-of: convention-workload-tolerations
    apps.tanzu.vmware.com/workload-type: web
    app.kubernetes.io/component: run
    carto.run/workload-name: convention-workload-tolerations
spec:
  template:
    metadata:
      annotations:
        autoscaling.knative.dev/minScale: "1"
        conventions.carto.run/applied-conventions: |-
          appliveview-sample/app-live-view-appflavour-check
          multi-purpose-convention/x95castle1.org-tolerations
          spring-boot-convention/auto-configure-actuators-check
          spring-boot-convention/app-live-view-appflavour-check
        developer.conventions/target-containers: workload
        kubectl.kubernetes.io/last-applied-configuration: |
          {"apiVersion":"carto.run/v1alpha1","kind":"Workload","metadata":{"annotations":{},"labels":{"app.kubernetes.io/part-of":"convention-workload-tolerations","apps.tanzu.vmware.com/workload-type":"web"},"name":"convention-workload-tolerations","namespace":"jeremy"},"spec":{"params":[{"name":"annotations","value":{"autoscaling.knative.dev/minScale":"1","x95castle1.org/tolerations":"[{\"key\":\"rabeyta\",\"operator\":\"Exists\",\"effect\":\"NoSchedule\"}]"}}],"source":{"git":{"ref":{"branch":"main"},"url":"https://github.com/carto-run/app-golang-kpack"}}}}
        x95castle1.org/tolerations: '[{"key":"rabeyta","operator":"Exists","effect":"NoSchedule"}]'
      labels:
        app.kubernetes.io/component: run
        app.kubernetes.io/part-of: convention-workload-tolerations
        apps.tanzu.vmware.com/workload-type: web
        carto.run/workload-name: convention-workload-tolerations
    spec:
      containers:
      - image: registry.harbor.learn.tapsme.org/tap-build/workloads/convention-workload-tolerations-jeremy@sha256:28474c1b0b92620539a96f91944dc5271a285c606646e733fd84ca31447c9123
        name: workload
        resources: {}
        securityContext:
          runAsUser: 1000
      serviceAccountName: default
      tolerations:
      - effect: NoSchedule
        key: rabeyta
        operator: Exists

