apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: sso-example-app-tap
  annotations:
    ootb.apps.tanzu.vmware.com/servicebinding-workload: "true"
    ootb.apps.tanzu.vmware.com/apidescriptor-ref: "true"
    kapp.k14s.io/change-rule: upsert after upserting servicebinding.io/ServiceBindings
  labels:
    app.kubernetes.io/part-of: sso-example-app-tap
    apps.tanzu.vmware.com/auto-configure-actuators: "true"
    apps.tanzu.vmware.com/workload-type: web
    app.kubernetes.io/component: run
    carto.run/workload-name: sso-example-app-tap
spec:
  template:
    metadata:
      annotations:
        apps.tanzu.vmware.com/correlationid: https://github.com/x95castle1/sso-example-app-tap.git?sub_path=/
        autoscaling.knative.dev/minScale: "1"
        developer.conventions/target-containers: workload
      labels:
        app.kubernetes.io/component: run
        app.kubernetes.io/part-of: sso-example-app-tap
        apps.tanzu.vmware.com/auto-configure-actuators: "true"
        apps.tanzu.vmware.com/workload-type: web
        carto.run/workload-name: sso-example-app-tap
    spec:
      containers:
      - env:
        - name: JAVA_TOOL_OPTIONS
          value: -Dorg.springframework.cloud.bindings.boot.enable=true
        - name: SPRING_PROFILES_ACTIVE
          value: cloud
        image: registry.harbor.learn.tapsme.org/tap-build/workloads/sso-example-app-tap-jeremy@sha256:9dd08e826b185836fdb86db0bfb843c529b719f7a4cea9b86bcdc25754f953b7
        name: workload
        resources: {}
        securityContext:
          runAsUser: 1000
      serviceAccountName: default

