apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: convention-workload-probes
  annotations:
    ootb.apps.tanzu.vmware.com/servicebinding-workload: "true"
    ootb.apps.tanzu.vmware.com/apidescriptor-ref: "true"
    kapp.k14s.io/change-rule: upsert after upserting servicebinding.io/ServiceBindings
  labels:
    app.kubernetes.io/part-of: convention-workload-probes
    apps.tanzu.vmware.com/language: golang
    apps.tanzu.vmware.com/workload-type: web
    app.kubernetes.io/component: run
    carto.run/workload-name: convention-workload-probes
spec:
  template:
    metadata:
      annotations:
        apps.tanzu.vmware.com/correlationid: https://github.com/carto-run/app-golang-kpack?sub_path=/
        autoscaling.knative.dev/minScale: "1"
        conventions.carto.run/applied-conventions: |-
          appliveview-sample/app-live-view-appflavour-check
          multi-purpose-convention/x95castle1.org-readiness
          spring-boot-convention/auto-configure-actuators-check
          spring-boot-convention/app-live-view-appflavour-check
        developer.conventions/target-containers: workload
        kubectl.kubernetes.io/last-applied-configuration: |
          {"apiVersion":"carto.run/v1alpha1","kind":"Workload","metadata":{"annotations":{},"labels":{"app.kubernetes.io/part-of":"convention-workload-probes","apps.tanzu.vmware.com/language":"golang","apps.tanzu.vmware.com/workload-type":"web"},"name":"convention-workload-probes","namespace":"jeremy"},"spec":{"params":[{"name":"annotations","value":{"autoscaling.knative.dev/minScale":"1","x95castle1.org/readinessProbe":"{\"httpGet\":{\"path\":\"/healthz\",\"port\":8080},\"initialDelaySeconds\":5,\"periodSeconds\":5}"}}],"source":{"git":{"ref":{"branch":"main"},"url":"https://github.com/carto-run/app-golang-kpack"}}}}
        x95castle1.org/readinessProbe: '{"httpGet":{"path":"/healthz","port":8080},"initialDelaySeconds":5,"periodSeconds":5}'
      labels:
        app.kubernetes.io/component: run
        app.kubernetes.io/part-of: convention-workload-probes
        apps.tanzu.vmware.com/language: golang
        apps.tanzu.vmware.com/workload-type: web
        carto.run/workload-name: convention-workload-probes
    spec:
      containers:
      - image: registry.harbor.learn.tapsme.org/tap-build/workloads/convention-workload-probes-jeremy@sha256:9e65bd9f1407d3cabe2a1c509443db295b1697df4ad23c79354762c024c5bde8
        name: workload
        readinessProbe:
          httpGet:
            path: /healthz
            port: 8080
          initialDelaySeconds: 5
          periodSeconds: 5
        resources: {}
        securityContext:
          runAsUser: 1000
      serviceAccountName: default

